# Generated by Django 3.2.12 on 2022-10-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu',
            name='dob',
            field=models.IntegerField(null=True),
        ),
    ]
