# Generated by Django 3.2.12 on 2022-10-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='created_by',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='updated_by',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
