# Generated by Django 4.1.2 on 2022-10-15 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0004_stu_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stu',
            name='user',
        ),
    ]
