# Generated by Django 4.1.2 on 2022-10-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0005_remove_stu_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
